api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "safety-gate-product-block"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/BlockExtension.jsx"
target = "admin.product-details.block.render"
