// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/api/product-safety-status": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/api/product-safety-check": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products/create": {
    params: {};
  };
  "/webhooks/products/update": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/billing/redirect": {
    params: {};
  };
  "/audit-report": {
    params: {};
  };
  "/manual-check": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/evidence": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/alerts": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/audit-report": {
    params: {};
  };
  "/app/manual-check": {
    params: {};
  };
  "/app/evidence": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/alerts": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/api/product-safety-status" | "/webhooks/customers/redact" | "/api/product-safety-check" | "/webhooks/app/uninstalled" | "/webhooks/products/create" | "/webhooks/products/update" | "/webhooks/shop/redact" | "/billing/redirect" | "/audit-report" | "/manual-check" | "/auth/login" | "/evidence" | "/settings" | "/alerts" | "/auth/*" | "/app" | "/app/audit-report" | "/app/manual-check" | "/app/evidence" | "/app/settings" | "/app/alerts";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/api.product-safety-status.ts": {
    id: "routes/api.product-safety-status";
    page: "/api/product-safety-status";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/api.product-safety-check.ts": {
    id: "routes/api.product-safety-check";
    page: "/api/product-safety-check";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products.create.tsx": {
    id: "routes/webhooks.products.create";
    page: "/webhooks/products/create";
  };
  "routes/webhooks.products.update.tsx": {
    id: "routes/webhooks.products.update";
    page: "/webhooks/products/update";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/billing.redirect.tsx": {
    id: "routes/billing.redirect";
    page: "/billing/redirect";
  };
  "routes/audit-report.tsx": {
    id: "routes/audit-report";
    page: "/audit-report";
  };
  "routes/manual-check.tsx": {
    id: "routes/manual-check";
    page: "/manual-check";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/evidence.tsx": {
    id: "routes/evidence";
    page: "/evidence";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/alerts.tsx": {
    id: "routes/alerts";
    page: "/alerts";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/audit-report" | "/app/manual-check" | "/app/evidence" | "/app/settings" | "/app/alerts";
  };
  "routes/app.audit-report.tsx": {
    id: "routes/app.audit-report";
    page: "/app/audit-report";
  };
  "routes/app.manual-check.tsx": {
    id: "routes/app.manual-check";
    page: "/app/manual-check";
  };
  "routes/app.evidence.tsx": {
    id: "routes/app.evidence";
    page: "/app/evidence";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.alerts.tsx": {
    id: "routes/app.alerts";
    page: "/app/alerts";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/api.product-safety-status": typeof import("./app/routes/api.product-safety-status.ts");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/api.product-safety-check": typeof import("./app/routes/api.product-safety-check.ts");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.products.create": typeof import("./app/routes/webhooks.products.create.tsx");
  "routes/webhooks.products.update": typeof import("./app/routes/webhooks.products.update.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/billing.redirect": typeof import("./app/routes/billing.redirect.tsx");
  "routes/audit-report": typeof import("./app/routes/audit-report.tsx");
  "routes/manual-check": typeof import("./app/routes/manual-check.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/evidence": typeof import("./app/routes/evidence.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/alerts": typeof import("./app/routes/alerts.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.audit-report": typeof import("./app/routes/app.audit-report.tsx");
  "routes/app.manual-check": typeof import("./app/routes/app.manual-check.tsx");
  "routes/app.evidence": typeof import("./app/routes/app.evidence.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.alerts": typeof import("./app/routes/app.alerts.tsx");
};